### ISSUE TITLE
Allow mixing physical and virtual machines

### ISSUE THREAD

**Issue by jiriprochazka** [jpirko/lnst#103]
In ENRT there is setup involving both bare metals and virtual machines. But mixing those is not allowed in LNST. Is there some valid justification for this behaviour and don't we want to change it so we can use both virtual and physical machines simultaneously?

**Comment by jtluka** [comment]
It is true that there are mixed setups in ENRT however all of the hosts
there are actually "baremetal" when used in Beaker job, no
"libvirt_domain" is used in these setups.
