### ISSUE TITLE
Exception raised when machine recipe contains invalid interface

### ISSUE THREAD

**Issue by jiriprochazka** [jpirko/lnst#107]
When machine recipe xml contains an invalid interface, running controller ends up in an exception.
```
2015-03-04 13:48:38    (testmachine1)        -   DEBUG: 
    Traceback (most recent call last):
      File "/root/lnst/lnst/Slave/NetTestSlave.py", line 794, in _process_msg
        result = method(*msg["args"])
      File "/root/lnst/lnst/Slave/NetTestSlave.py", line 164, in set_unmapped_device_down
        dev.down()
    AttributeError: 'NoneType' object has no attribute 'down'
```

It would be nice to handle this differently - eg. ignoring invalid interfaces with Warning message in log, or ending up in Error message with info, which interfaces are invalid.

**Comment by jtluka** [comment]
I agree that this should be fixed, on the other hand it's not good to have this as warning and ignore the device. The controller should exit with an error message.

**Comment by jiriprochazka** [comment]
same as https://github.com/jpirko/lnst/issues/122
