### ISSUE TITLE
add check of controller-slave compatibility

### ISSUE THREAD

**Issue by jtluka** [jpirko/lnst#136]
Sometimes we run different versions (git and rpm installed) of slave and controller by mistake. Checking the version using e.g. hello() method will easily identify such setups.

**Comment by jbenc** [comment]
Run into this bug today. It's impossible to figure out what's going on if you get a splat like:

2016-04-07 14:18:00       (localhost)        -    INFO:      error message: CommandException: Recieved an error message from slave client: Method 'wait_interface_init' not supported.  

lnst should detect that slave is incompatible and give a meaningful error message. It was impossible to figure out what happened without a help from the developers.

**Comment by olichtne** [comment]
This functionality was added in 05fc90d66071c90c9c8cc1bc3bf294cf5a1349d8. Unless there are any other commets I'd say we can close this issue.
