### ISSUE TITLE
remove HostAPI.get_ip() and similar interface related methods

### ISSUE THREAD

**Issue by jtluka** [jpirko/lnst#137]
We should remove these since we already have HostAPI.get_iface() method that returns Iface object that provides the same API.

**Comment by jiriprochazka** [comment]
After short discussion on mailing list we decided to do following:
- Leave HostAPI.get_ip() method, but mark it as deprecated (meaning Warning log message is shown when method is used).
- Rename InterfaceAPI.get_ip_addr() and InterfaceAPI.get_ip_addrs() to InterfaceAPI.get_ip() and InterfaceAPI.get_ips(), but leave InterfaceAPI.get_ip_addr() and InterfaceAPI.get_ip_addrs() as alias pointing to new functions
- Mark InterfaceAPI.get_ip_addr() and InterfaceAPI.get_ip_addrs() as deprecated

Implemented in fcd27ad8bc7e03db6c0b12094fe4fc01057e77e2 and acf594554aeb6e7dba54e30b1a3161c63924f5a5

Similar methods will face the same fate "soonish"

**Comment by jiriprochazka** [comment]
HostAPI methods get_hwaddr(), get_devname() and get_prefix() has been marked as obsolete in patch f3d8a1b3f84b81f36f3f947f6836764c8eb0a495
