### ISSUE TITLE
secure connections to lnst slave by ssl with auth

### ISSUE THREAD

**Issue by jpirko** [jpirko/lnst#141]
Today, running lnst-slave a big backdoor into system. Attacker can do anything. So please secure connections to lnst-slave and introduce auth, best would be probably using certs.

**Comment by olichtne** [comment]
This was added in patches 6e72f1ad44c0db787e2b60c38367f6db907aa9ac..d8d3967f7b3448c25c68fbfb2ac5379adb632d34
