### ISSUE TITLE
lnst-ctl listpool

### ISSUE THREAD

**Issue by jtluka** [jpirko/lnst#149]
It would be nice to list pool of test machines based on user configuration.

Something like:
```
# lnst-ctl listpool

testmachine1
   iface: 1   00:01:02:0a:0b:0c
   iface: 2   11:01:02:0a:0b:0c

testmachine2
   iface: 1   aa:01:02:0a:0b:0c
   iface: 2   bb:01:02:0a:0b:0c
```

**Comment by olichtne** [comment]
This was introduced in c421f5cce57cba9c3e49d5ad81880cc25305507e and then fixed up in a couple of followup commits. Should be working, if any bugs are found we can open new issues for them.
