### ISSUE TITLE
LNST tries to connect to PerfRepo even if there's no url specified

### ISSUE THREAD

**Issue by aloughlam** [jpirko/lnst#154]
when trying lnst without interest in submitting results to perfrepo, I didn't specify the url, yet lnst tries to connect and test fail:
ERROR: Invalid URL u'/rest/test/id/bos_ab_bond_ipv4_tcp': No schema supplied. Perhaps you meant http:///rest/test/id/bos_ab_bond_ipv4_tcp?

**Comment by jtluka** [comment]
I think this happens only if there are mapping files available. Still, we should catch this exception. Do you have a traceback available?

**Comment by olichtne** [comment]
It's a problem with how I use the requests library... There's no checking if any url was supplied or if the connection is working... It just goes straight to sending a request and that should be fixed more properly than just catching this exception.

**Comment by olichtne** [comment]
Instead of fixing this in the LNST repository I'll fix this in the split PerfRepo library that I'm working on here: [olichtne/python-perfrepo](http://www.github.com/olichtne/python-perfrepo)

Related issue #155

**Comment by olichtne** [comment]
This should be fixed in the upstream python-perfrepo library, so I'm closing this issue.
