### ISSUE TITLE
replace subprocess.check_output with python2.6 equivalent

### ISSUE THREAD

**Issue by jtluka** [jpirko/lnst#174]
Patch that added slave-controller version checking caused regression on RHEL6 distro where Python2.6 only is available.

Method subprocess.check_output() is available from Python2.7 and higher.

Since we want LNST working on RHEL6 we need to replace the code with something from python2.6.

**Comment by jtluka** [comment]
I belive this is the code we need to use:
https://docs.python.org/2.6/library/subprocess.html#replacing-bin-sh-shell-backquote

**Comment by jiriprochazka** [comment]
patch sent @ https://lists.fedorahosted.org/archives/list/lnst-developers@lists.fedorahosted.org/thread/JJOKHLJBTRY5IPPMIRWMINUXS5HREMRE/
