### ISSUE TITLE
how to build a pool to deal with such case

### ISSUE THREAD

**Issue by fun2yang** [jpirko/lnst#192]
<lnstrecipe>
    <define>
        <alias name="ipv" value="both" />
        <alias name="mtu" value="1500" />
        <alias name="netperf_duration" value="60" />
        <alias name="nperf_reserve" value="20" />
        <alias name="nperf_confidence" value="99,5" />
        <alias name="nperf_max_runs" value="5"/>
        <alias name="nperf_mode" value="default"/>
        <alias name="nperf_num_parallel" value="2"/>
        <alias name="nperf_debug" value="0"/>
        <alias name="nperf_max_dev" value="20%"/>
        <alias name="nperf_protocols" value="tcp udp sctp"/>
        <alias name="mapping_file" value="3_vlans.mapping" />
        <alias name="vlan10_net" value="192.168.10"/>
        <alias name="vlan10_tag" value="10"/>
        <alias name="vlan20_net" value="192.168.20"/>
        <alias name="vlan20_tag" value="20"/>
        <alias name="vlan30_net" value="192.168.30"/>
        <alias name="vlan30_tag" value="30"/>
        <alias name="driver" value="ixgbe"/>
        <alias name="official_result" value="no" />
        <alias name="adaptive_coalescing_off" value="no"/>
    </define>
    <network>
        <host id="testmachine1">
            <interfaces>
                <eth id="eth1" label="tnet">
                    <params>
                        <param name="driver" value="{$driver}"/>
                    </params>
                </eth>
                <vlan id="vlan10">
                    <options>
                        <option name="vlan_tci" value="{$vlan10_tag}" />
                    </options>
                    <slaves>
                        <slave id="eth1" />
                    </slaves>
                    <addresses>
                        <address value="{$vlan10_net}.1/24" />
                        <address value="fc00:0:0:10::1/64" />
                    </addresses>
                </vlan>
                <vlan id="vlan20">
                    <options>
                        <option name="vlan_tci" value="{$vlan20_tag}" />
                    </options>
                    <slaves>
                        <slave id="eth1" />
                    </slaves>
                    <addresses>
                        <address value="{$vlan20_net}.1/24" />
                        <address value="fc00:0:0:20::1/64" />
                    </addresses>
                </vlan>
                <vlan id="vlan30">
                    <options>
                        <option name="vlan_tci" value="{$vlan30_tag}" />
                    </options>
                    <slaves>
                        <slave id="eth1" />
                    </slaves>
                    <addresses>
                        <address value="{$vlan30_net}.1/24" />
                        <address value="fc00:0:0:30::1/64" />
                    </addresses>
                </vlan>
            </interfaces>
        </host>
        <host id="testmachine2">
            <interfaces>
                <eth id="eth1" label="tnet">
                    <params>
                        <param name="driver" value="{$driver}"/>
                    </params>
                </eth>
                <vlan id="vlan10">
                    <options>
                        <option name="vlan_tci" value="{$vlan10_tag}" />
                    </options>
                    <slaves>
                        <slave id="eth1" />
                    </slaves>
                    <addresses>
                        <address value="{$vlan10_net}.2/24" />
                        <address value="fc00:0:0:10::2/64" />
                    </addresses>
                </vlan>
                <vlan id="vlan20">
                    <options>
                        <option name="vlan_tci" value="{$vlan20_tag}" />
                    </options>
                    <slaves>
                        <slave id="eth1" />
                    </slaves>
                    <addresses>
                        <address value="{$vlan20_net}.2/24" />
                        <address value="fc00:0:0:20::2/64" />
                    </addresses>
                </vlan>
                <vlan id="vlan30">
                    <options>
                        <option name="vlan_tci" value="{$vlan30_tag}" />
                    </options>
                    <slaves>
                        <slave id="eth1" />
                    </slaves>
                    <addresses>
                        <address value="{$vlan30_net}.2/24" />
                        <address value="fc00:0:0:30::2/64" />
                    </addresses>
                </vlan>
            </interfaces>
        </host>
    </network>

    <task python="3_vlans.py" />
</lnstrecipe>

**Comment by fun2yang** [comment]
/root/lnst/recipes/regression_tests/phase1/3_vlans.xml

**Comment by olichtne** [comment]
Hi,

the 3_vlans.xml recipe requires just 2 hosts with one test ethernet each. The vlans get configured automatically so an example pool that should work could look like this:
### host1.xml
```xml
<slavemachine>
    <params>
        <param name="hostname" value="HOSTNAME_OR_IP1"/>
    </params>
    <interfaces>
        <eth id="1" label="test_net1">
            <params>
                <param name="hwaddr" value="TEST_NIC_MACADDR1"/>
            </params>
        </eth>
    </interfaces>
</slavemachine>
```
### host2.xml
```xml
<slavemachine>
    <params>
        <param name="hostname" value="HOSTNAME_OR_IP2"/>
    </params>
    <interfaces>
        <eth id="1" label="test_net1">
            <params>
                <param name="hwaddr" value="TEST_NIC_MACADDR2"/>
            </params>
        </eth>
    </interfaces>
</slavemachine>
```

Btw we mostly use issues to track bugs, not generic help questions, next time please use the mailing list lnst-developers@lists.fedorahosted.org
