### ISSUE TITLE
netns deconfiguration fails when lnst-slave killed from terminal

### ISSUE THREAD

**Issue by olichtne** [jpirko/lnst#86]
The problem occurs when the slave is configured by config_only and the user decides to ctrl+c the slave. The signal is sent to all processes (all network namespaces) resulting in deconfiguration races.

**Comment by olichtne** [comment]
[patch posted](https://lists.fedorahosted.org/pipermail/lnst-developers/2015-January/002578.html)

**Comment by jtluka** [comment]
Fixed by 110ab74f9c4f9a60fd42d029a5ea67e04af3f3b9
